package codegen_test

import (
	"go/token"
	"go/types"
	"testing"

	"github.com/sunboyy/repogen/internal/code"
	"github.com/sunboyy/repogen/internal/codegen"
	"github.com/sunboyy/repogen/internal/testutils"
)

const expectedBuildCode = `// Code generated by repogen. DO NOT EDIT.
package user

import (
	_ "context"

	"go.mongodb.org/mongo-driver/bson/primitive"
	_ "go.mongodb.org/mongo-driver/mongo/options"
)

type User struct {
	ID       primitive.ObjectID ` + "`bson:\"id\" json:\"id,omitempty\"`" + `
	Username string
}

func NewUser(username string) User {
	return User{
		ID:       primitive.NewObjectID(),
		Username: username,
	}
}

func (u User) IDHex() string {
	return u.ID.Hex()
}
`

func TestBuilderBuild(t *testing.T) {
	builder := codegen.NewBuilder("repogen", "user", [][]codegen.Import{
		{
			{
				Name: "_",
				Path: "context",
			},
		},
		{
			{
				Path: "go.mongodb.org/mongo-driver/bson/primitive",
			},
			{
				Name: "_",
				Path: "go.mongodb.org/mongo-driver/mongo/options",
			},
		},
	})
	builder.AddImplementer(codegen.StructBuilder{
		Pkg:  testutils.Pkg,
		Name: "User",
		Fields: []code.StructField{
			{
				Var: types.NewVar(token.NoPos, nil, "ID", testutils.TypeObjectIDNamed),
				Tag: `bson:"id" json:"id,omitempty"`,
			},
			{
				Var: types.NewVar(token.NoPos, nil, "Username", code.TypeString),
			},
		},
	})
	builder.AddImplementer(codegen.FunctionBuilder{
		Pkg:  testutils.Pkg,
		Name: "NewUser",
		Params: types.NewTuple(
			types.NewVar(token.NoPos, nil, "username", code.TypeString),
		),
		Returns: []types.Type{
			types.NewNamed(types.NewTypeName(token.NoPos, nil, "User", nil), nil, nil),
		},
		Body: codegen.FunctionBody{
			codegen.ReturnStatement{
				codegen.StructStatement{
					Type: "User",
					Pairs: []codegen.StructFieldPair{
						{
							Key: "ID",
							Value: codegen.ChainStatement{
								codegen.Identifier("primitive"),
								codegen.CallStatement{
									FuncName: "NewObjectID",
								},
							},
						},
						{
							Key:   "Username",
							Value: codegen.Identifier("username"),
						},
					},
				},
			},
		},
	})
	builder.AddImplementer(codegen.MethodBuilder{
		Pkg:      testutils.Pkg,
		Receiver: codegen.MethodReceiver{Name: "u", TypeName: "User"},
		Name:     "IDHex",
		Params:   nil,
		Returns:  []types.Type{code.TypeString},
		Body: codegen.FunctionBody{
			codegen.ReturnStatement{
				codegen.ChainStatement{
					codegen.Identifier("u"),
					codegen.Identifier("ID"),
					codegen.CallStatement{FuncName: "Hex"},
				},
			},
		},
	})

	generatedCode, err := builder.Build()
	if err != nil {
		t.Fatal(err)
	}
	if err := testutils.ExpectMultiLineString(expectedBuildCode, generatedCode); err != nil {
		t.Error(err)
	}
}
