name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go get -u golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -covermode=count -coverprofile=cover.out

    - name: Vet & Lint
      run: |
        go vet ./...
        golint -set_exit_status ./...

    - uses: codecov/codecov-action@v1
      with:
        flags: unittests
